### ISSUE TITLE
Link to woven fabrics (texture_1 and texture_2) dataset

### ISSUE THREAD

**Issue by hmf** [PabloMaj/Unsupervised-Anomaly-Detection-with-SSIM-AE#1]
I have been trying to get hold of this data:

> woven fabrics (texture_1 and texture_2): https://www.mvtec.com/company/research/publications/

However, I see only a list of articles. I have looked at the second reference and see no mention of fabrics. Is there a more specific link to the data set I can use?

TIA

**Comment by linsole** [comment]
Actually it is in the website, following the 2019 paper: Improving Unsupervised Defect Segmentation by Applying Structural Similarity to Autoencoders. You can download the dataset by clicking the link following the DOI.

**Comment by hmf** [comment]
@linsole thank you very much for the reference. I now have the data.
